# Generated by Django 4.0.2 on 2022-02-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_server_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='access',
            field=models.CharField(default='C:\\GATE', max_length=1024),
        ),
    ]
