# Generated by Django 4.0.2 on 2022-02-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_server_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='secure',
            new_name='is_secure',
        ),
    ]
