# Generated by Django 4.0.2 on 2022-02-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_server_created_on_useraccess_activated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookmark',
            name='path',
            field=models.CharField(max_length=1024),
        ),
    ]
