# Generated by Django 4.0.2 on 2022-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_server_code_alter_server_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='valid_till',
            field=models.DateTimeField(null=True),
        ),
    ]
