# Generated by Django 4.0.2 on 2022-02-18 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_useraccess_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.server'),
        ),
    ]
