# Generated by Django 4.0.2 on 2022-02-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_useraccess_is_admin_alter_useraccess_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='admin',
        ),
    ]
