# Generated by Django 4.0.2 on 2022-02-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_server_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
