# Generated by Django 4.0.2 on 2022-02-22 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_useraccess_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccess',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccess',
            name='latest_access',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
